export const sessionConstants = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const offerConstants = {
  GET_ALL_OFFERS_REQUEST: 'GET_ALL_OFFERS_REQUEST',
  GET_ALL_OFFERS_SUCCESS: 'GET_ALL_OFFERS_SUCCESS',
  GET_ALL_OFFERS_FAILURE: 'GET_ALL_OFFERS_FAILURE',

  GET_OFFERS_BY_TYPE_REQUEST: 'GET_OFFERS_BY_TYPE_REQUST',
  GET_OFFERS_BY_TYPE_SUCCESS: 'GET_OFFERS_BY_TYPE_SUCCSS',
  GET_OFFERS_BY_TYPE_FAILURE: 'GET_OFFERS_BY_TYPE_FAILURE',

  GET_OFFER_BY_ID_REQUEST: 'GET_OFFER_BY_ID_REQUEST',
  GET_OFFER_BY_ID_SUCCESS: 'GET_OFFER_BY_ID_SUCCESS',
  GET_OFFER_BY_ID_FAILURE: 'GET_OFFER_BY_ID_FAILURE',
};

export const profileConstants = {
  ADD_OFFER_REQUEST: 'ADD_OFFER_REQUEST',
  ADD_OFFER_SUCCESS: 'ADD_OFFER_SUCCESS',
  ADD_OFFER_FAILURE: 'ADD_OFFER_FAILURE',
  GET_EMPLOYER_OFFERS_REQUEST: 'GET_EMPLOYER_OFFERS_REQUEST',
  GET_EMPLOYER_OFFERS_SUCCESS: 'GET_EMPLOYER_OFFERS_SUCCESS',
  GET_EMPLOYER_OFFERS_FAILURE: 'GET_EMPLOYER_OFFERS_FAILURE',
};

export const uiConstants = {
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  CLEAR_CURRENT_OFFER: 'CLEAR_CURRENT_OFFER',
  TOGGLE_MOBILE_NAVIGATION: 'TOGGLE_MOBILE_NAVIGATION',
  TOGGLE_SEARCH_BAR: 'TOGGLE_SEARCH_BAR',
  IS_MOBILE_VIEW: 'IS_MOBILE_VIEW',
};
